name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Gradle wrapper validation
      uses: gradle/wrapper-validation-action@v1.0.4
    - name: Build with Gradle
      run: ./gradlew build
